import { useEffect, useState } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { getAdminProjects, getAdminUsers, resetUserPassword, updateAdminProject, updateAdminUser } from '../lib/api'

export default function AdminPage({ session, refreshSession }) {
  const [users, setUsers] = useState([]); const [projects, setProjects] = useState([]); const [message, setMessage] = useState('')
  if (session.user.globalRole !== 'SUPERADMIN') return <Navigate to="/" replace />
  async function load() { try { const [nextUsers, nextProjects] = await Promise.all([getAdminUsers(), getAdminProjects()]); setUsers(nextUsers); setProjects(nextProjects) } catch (error) { setMessage(error.message) } }
  useEffect(() => { load() }, [])
  async function userChange(id, data) { try { await updateAdminUser(id, data); await load(); await refreshSession() } catch (error) { setMessage(error.message) } }
  async function reset(id) { if (!confirm('Se cerrarán todas las sesiones del usuario. ¿Continuar?')) return; try { const result = await resetUserPassword(id); setMessage(`Contraseña temporal: ${result.temporaryPassword}`) } catch (error) { setMessage(error.message) } }
  async function projectChange(id, data) { try { await updateAdminProject(id, data); await load(); await refreshSession() } catch (error) { setMessage(error.message) } }
  return <main className="page admin-page"><div className="section-heading admin-heading"><div><h1>Administración global</h1><p>Usuarios y proyectos de toda la plataforma.</p></div><Link className="primary-link" to="/">Volver a proyectos</Link></div>{message && <div className="panel form-message admin-message">{message}</div>}<section className="panel"><h2>Usuarios</h2>{users.map(item => <div className="admin-row admin-user-row" key={item.id}><div><strong>{item.displayName || item.email}</strong><small>{item.email} · {item.memberships.length} proyecto(s){item.disabledAt ? ' · BLOQUEADO' : ''}</small></div><div><select value={item.globalRole} onChange={e => userChange(item.id, { globalRole: e.target.value })}><option value="USER">USER</option><option value="SUPERADMIN">SUPERADMIN</option></select><button onClick={() => userChange(item.id, { blocked: !item.disabledAt })}>{item.disabledAt ? 'Desbloquear' : 'Bloquear'}</button><button onClick={() => reset(item.id)}>Blanquear clave</button></div></div>)}</section><section className="panel"><h2>Proyectos</h2>{projects.map(project => <div className="admin-row admin-user-row" key={project.id}><div><strong>{project.name}</strong><small>{project.slug} · {project._count.memberships} miembros · {project._count.documents} documentos{project.archivedAt ? ' · ELIMINADO' : project.blockedAt ? ' · BLOQUEADO' : project.isReadOnly ? ' · SOLO LECTURA' : ''}</small></div><div><button disabled={Boolean(project.archivedAt)} onClick={() => projectChange(project.id, { isReadOnly: !project.isReadOnly })}>{project.isReadOnly ? 'Permitir edición' : 'Solo lectura'}</button><button disabled={Boolean(project.archivedAt)} onClick={() => projectChange(project.id, { blocked: !project.blockedAt })}>{project.blockedAt ? 'Desbloquear' : 'Bloquear'}</button><button className="danger" onClick={() => projectChange(project.id, { archived: !project.archivedAt })}>{project.archivedAt ? 'Reactivar' : 'Eliminar'}</button></div></div>)}</section></main>
}
