import assert from 'node:assert/strict'
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
const base = process.env.API_URL || 'http://localhost:3000/api'
async function login(email) {
  const response = await fetch(`${base}/auth/login`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password: 'Admin123!' }) })
  assert.equal(response.status, 204)
  return response.headers.get('set-cookie').split(';')[0]
}
const call = (path, cookie, options = {}) => fetch(`${base}${path}`, { ...options, headers: { cookie, 'content-type': 'application/json', ...options.headers } })
const viewerCookie = await login('viewer@example.com')
const adminCookie = await login('admin@example.com')
const viewerSession = await (await call('/auth/session', viewerCookie)).json()
const adminSession = await (await call('/auth/session', adminCookie)).json()
const allowedId = viewerSession.projects[0].id
const privateId = adminSession.projects.find(project => project.slug === 'tenant-privado').id
assert.equal((await call(`/projects/${allowedId}/documents`, viewerCookie)).status, 200)
assert.equal((await call(`/projects/${privateId}/documents`, viewerCookie)).status, 404)
assert.equal((await call(`/projects/${allowedId}/documents`, viewerCookie, { method: 'POST', body: JSON.stringify({ slug: 'forbidden', title: 'Forbidden', section: 'QA', markdown: 'No' }) })).status, 403)
const members = await (await call(`/projects/${privateId}/members`, adminCookie)).json()
const lastAdmin = members.find(member => member.role === 'ADMIN')
assert.equal((await call(`/projects/${privateId}/members/${lastAdmin.user.id}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ role: 'VIEWER' }) })).status, 409)
assert.equal((await call('/auth/logout', viewerCookie, { method: 'POST' })).status, 204)
assert.equal((await call('/auth/session', viewerCookie)).status, 401)
const registerEmail = `smoke-${Date.now()}@example.com`
const registrationProject = await prisma.project.create({ data: { name: 'Smoke registration', slug: `smoke-registration-${Date.now()}` } })
const registerResponse = await fetch(`${base}/auth/register`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: registerEmail, displayName: 'Smoke User', password: 'SmokePass123!' }) })
assert.equal(registerResponse.status, 201)
const registerCookie = registerResponse.headers.get('set-cookie').split(';')[0]
assert.equal((await call('/access-requests', registerCookie, { method: 'POST', body: JSON.stringify({ projectIds: [registrationProject.id] }) })).status, 204)
const pendingSession = await (await call('/auth/session', registerCookie)).json()
assert.equal(pendingSession.projects.length, 0)
assert.equal((await call(`/projects/${registrationProject.id}/access-requests/${pendingSession.accessRequests[0].id}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ status: 'APPROVED' }) })).status, 204)
assert.equal((await call(`/projects/${registrationProject.id}/members/${pendingSession.user.id}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ role: 'ADMIN' }) })).status, 200)
const registeredSession = await (await call('/auth/session', registerCookie)).json()
assert.equal(registeredSession.projects.length, 1)
assert.equal(registeredSession.projects[0].role, 'ADMIN')
const registeredUserId = registeredSession.user.id
const registeredProjectId = registeredSession.projects[0].id
assert.equal((await fetch(`${base}/membership-projects`)).status, 401)
assert.deepEqual((await (await call('/membership-projects', registerCookie)).json()).map(project => project.id), [registeredProjectId])
assert.ok((await (await call('/membership-projects', adminCookie)).json()).some(project => project.id === privateId))
assert.equal((await call(`/projects/${privateId}/members`, registerCookie)).status, 404)
const memberPath = `/projects/${registeredProjectId}/members`
assert.equal((await call(memberPath, registerCookie, { method: 'POST', body: JSON.stringify({ email: 'viewer@example.com', role: 'VIEWER' }) })).status, 201)
assert.equal((await call(`${memberPath}/${viewerSession.user.id}`, registerCookie, { method: 'PATCH', body: JSON.stringify({ role: 'EDITOR' }) })).status, 200)
assert.equal((await call(`${memberPath}/${viewerSession.user.id}`, registerCookie, { method: 'DELETE' })).status, 204)
assert.equal((await call(`${memberPath}/${registeredUserId}`, registerCookie, { method: 'DELETE' })).status, 409)
assert.equal((await call('/admin/users', adminCookie)).status, 200)
assert.equal((await call('/admin/projects', adminCookie)).status, 200)
assert.equal((await call(`/admin/projects/${registeredProjectId}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ isReadOnly: true }) })).status, 200)
assert.equal((await call(`/projects/${registeredProjectId}/documents`, registerCookie, { method: 'POST', body: JSON.stringify({ slug: 'readonly', title: 'Readonly', section: 'QA', markdown: 'No' }) })).status, 423)
await call(`/admin/projects/${registeredProjectId}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ isReadOnly: false, blocked: true }) })
assert.equal((await call(`/projects/${registeredProjectId}/documents`, registerCookie)).status, 423)
assert.equal((await call(memberPath, adminCookie)).status, 200)
assert.equal((await call(memberPath, registerCookie)).status, 423)
assert.deepEqual(await (await call('/membership-projects', registerCookie)).json(), [])
await call(`/admin/projects/${registeredProjectId}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ blocked: false, archived: true }) })
assert.equal((await call(`/projects/${registeredProjectId}/documents`, registerCookie)).status, 423)
assert.equal((await call(memberPath, adminCookie)).status, 200)
assert.equal((await call(memberPath, registerCookie)).status, 423)
assert.deepEqual(await (await call('/membership-projects', registerCookie)).json(), [])
await call(`/admin/projects/${registeredProjectId}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ archived: false }) })
const deletePath = `/admin/projects/${registeredProjectId}`
const deleteOptions = { method: 'DELETE', body: JSON.stringify({ slug: registeredSession.projects[0].slug }) }
assert.equal((await fetch(`${base}${deletePath}`, { ...deleteOptions, headers: { 'content-type': 'application/json' } })).status, 401)
assert.equal((await call(deletePath, registerCookie, deleteOptions)).status, 403)
const editorCookie = await login('editor@example.com')
const freshViewerCookie = await login('viewer@example.com')
assert.deepEqual(await (await call('/membership-projects', freshViewerCookie)).json(), [])
assert.deepEqual(await (await call('/membership-projects', editorCookie)).json(), [])
assert.equal((await call(`/projects/${allowedId}/members`, editorCookie, { method: 'POST', body: JSON.stringify({ email: registerEmail, role: 'VIEWER' }) })).status, 403)
assert.equal((await call(deletePath, editorCookie, deleteOptions)).status, 403)
assert.equal((await call(deletePath, freshViewerCookie, deleteOptions)).status, 403)
assert.equal((await call(deletePath, adminCookie, { method: 'DELETE', body: '{}' })).status, 400)
assert.equal((await call(deletePath, adminCookie, { method: 'DELETE', body: JSON.stringify({ slug: 'wrong-confirmation' }) })).status, 400)
assert.ok(await prisma.project.findUnique({ where: { id: registeredProjectId } }))
assert.equal((await call(`/projects/${registeredProjectId}/documents`, registerCookie, { method: 'POST', body: JSON.stringify({ slug: 'delete-test', title: 'Delete test', section: 'QA', markdown: 'Temporary document' }) })).status, 201)
const untouchedProject = await prisma.project.findUnique({ where: { id: privateId }, include: { _count: { select: { documents: true, memberships: true } } } })
const resetResponse = await call(`/admin/users/${registeredUserId}/reset-password`, adminCookie, { method: 'POST' })
assert.equal(resetResponse.status, 200)
const { temporaryPassword } = await resetResponse.json()
assert.match(temporaryPassword, /^Tmp-/)
assert.equal((await call('/auth/session', registerCookie)).status, 401)
assert.equal((await call(`/admin/users/${registeredUserId}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ blocked: true }) })).status, 200)
assert.equal((await call(`/admin/users/${registeredUserId}`, adminCookie, { method: 'PATCH', body: JSON.stringify({ blocked: false }) })).status, 200)
assert.equal((await call(deletePath, adminCookie, deleteOptions)).status, 204)
assert.equal(await prisma.project.findUnique({ where: { id: registeredProjectId } }), null)
assert.equal(await prisma.document.count({ where: { projectId: registeredProjectId } }), 0)
assert.equal(await prisma.projectMembership.count({ where: { projectId: registeredProjectId } }), 0)
assert.ok(await prisma.user.findUnique({ where: { id: registeredUserId } }))
assert.deepEqual(await prisma.project.findUnique({ where: { id: privateId }, include: { _count: { select: { documents: true, memberships: true } } } }), untouchedProject)
assert.equal((await call(deletePath, adminCookie, deleteOptions)).status, 404)
assert.equal((await call(`/projects/${registeredProjectId}/documents`, adminCookie)).status, 404)
assert.ok(!(await (await call('/admin/projects', adminCookie)).json()).some(project => project.id === registeredProjectId))
assert.ok(!(await (await call('/auth/session', adminCookie)).json()).projects.some(project => project.id === registeredProjectId))
await call('/auth/logout', editorCookie, { method: 'POST' })
await call('/auth/logout', freshViewerCookie, { method: 'POST' })
await prisma.user.delete({ where: { email: registerEmail } })
await prisma.$disconnect()
console.log('Smoke RBAC OK: registro, cambio de proyecto, usuarios, estados de proyecto, aislamiento, borrado definitivo y logout.')
